/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cMTg15JZRUW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

**/
'use client'

import PieChart from "./graphs/pie-chart";
import BarChart from "./graphs/bar-chart";
import LineChart from "./graphs/line-chart";

export function AnalyticsHomepage() {

  return (
    <div className="">

      <PieChart />
      <BarChart />
      <LineChart />
    </div>
  )
}
